// Code generated by girgen. DO NOT EDIT.

package flatpak

import (
	_ "runtime/cgo"

	"github.com/diamondburned/gotk4/pkg/glib/v2"
)

// #cgo pkg-config: flatpak gdk-pixbuf-2.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <flatpak.h>
import "C"

// The function returns the following values:
//
func ErrorQuark() glib.Quark {
	var _cret C.GQuark // in

	_cret = C.flatpak_error_quark()

	var _quark glib.Quark // out

	_quark = uint32(_cret)

	return _quark
}

// The function returns the following values:
//
func PortalErrorQuark() glib.Quark {
	var _cret C.GQuark // in

	_cret = C.flatpak_portal_error_quark()

	var _quark glib.Quark // out

	_quark = uint32(_cret)

	return _quark
}
