// Code generated by girgen. DO NOT EDIT.

package flatpak

// #include <stdlib.h>
// #include <flatpak.h>
import "C"

// MAJOR_VERSION: major version.
const MAJOR_VERSION = 1

// MICRO_VERSION: micro version.
const MICRO_VERSION = 7

// MINOR_VERSION: minor version.
const MINOR_VERSION = 12
